### ISSUE TITLE
Skipping on rebelion

### ISSUE THREAD

**Issue by myusernameis69** [milxss/universal_log_parser#2]
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/key_datas.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/settingss.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/usertag.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/59CD46517BE08DA0s.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/A7FDF864FBC10B77s.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/B027A53ABB3B4383s.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/countries.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/prefix.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/A7FDF864FBC10B77/configs.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/D877F783D5D3EF8C/configs.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/HU[63B68E8B4439C38B4A31EED5198473DF] [2023-11-01T11_57_58.8718608-07_00]]/Telegram/Profile_1/D877F783D5D3EF8C/maps.IGHmUlm7L. Skipping...
Error: Unable to read file /root/logs/ZA[4F775A793B9F419D809B0E870D89C7C7] [2023-11-03T09_30_15.7609675]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/AR[BAC3C6AE154CA9FD30942BEE629DC473] [2023-10-21T13_02_45.6099110-07_00]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/DZ[25BA590C04A11EBD7C5818D92FCD4917] [2023-11-02T14_58_30.3478850]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/PH[38F7992D47A8BA3F3D5D96B5E96B10A9] [2023-11-06T06_08_14.7547680]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/MA[FA80B87E554AF9AA75E53220675BA633] [2023-11-02T06_38_07.8743522]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/MU[2B42D8BAC8D4EA7ACB15BF2699A33E51] [2023-11-04T11_59_01.1290407]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/MU[2B42D8BAC8D4EA7ACB15BF2699A33E51] [2023-11-04T11_59_01.1290407]]/Steam/ssfn62036885914727053. Skipping...
Error: Unable to read file /root/logs/MU[2B42D8BAC8D4EA7ACB15BF2699A33E51] [2023-11-04T11_59_01.1290407]]/Steam/ssfn5630343969833964887. Skipping...
Error: Unable to read file /root/logs/TR[AD7A4DD70258C36C2D947F54AAC2E682] [2023-11-03T09_32_41.8179690]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/TR[AD7A4DD70258C36C2D947F54AAC2E682] [2023-11-03T09_32_41.8179690]]/Steam/ssfn60525774751869332. Skipping...
Error: Unable to read file /root/logs/TR[AD7A4DD70258C36C2D947F54AAC2E682] [2023-11-03T09_32_41.8179690]]/Steam/coplay_76561199204605984.vdf. Skipping...
Error: Unable to read file /root/logs/TR[AD7A4DD70258C36C2D947F54AAC2E682] [2023-11-03T09_32_41.8179690]]/Steam/ssfn5326350995073253383. Skipping...
Error: Unable to read file /root/logs/PH[27B05E0638F080608B65B01B886A7239] [2023-11-03T03_42_49.9042558]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/PH[27B05E0638F080608B65B01B886A7239] [2023-11-03T03_42_49.9042558]]/Steam/coplay_76561198341550771.vdf. Skipping...
Error: Unable to read file /root/logs/PH[27B05E0638F080608B65B01B886A7239] [2023-11-03T03_42_49.9042558]]/Steam/coplay_76561199051844894.vdf. Skipping...
Error: Unable to read file /root/logs/PH[27B05E0638F080608B65B01B886A7239] [2023-11-03T03_42_49.9042558]]/Steam/coplay_76561198371647299.vdf. Skipping...
Error: Unable to read file /root/logs/PH[27B05E0638F080608B65B01B886A7239] [2023-11-03T03_42_49.9042558]]/Steam/coplay_76561198325939931.vdf. Skipping...
Error: Unable to read file /root/logs/NA[6FDA8C681B68060DF595589CF9667DCB] [2023-11-06T23_57_01.6417113]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/CL[E3DA5DFC1C5413BB30AC19B362515060] [2023-11-01T10_35_05.2225313-07_00]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/DO[1DB269C5C10A5F7B92CD227B2D3E0DA1] [2023-11-01T09_27_44.9803261]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/BR[3EC09DDC3C287A4E4E0CCA21D0069C1C] [2023-11-03T17_10_13.3433782-07_00]]/RDX.jpg. Skipping...
Error: Unable to read file /root/logs/BR[3EC09DDC3C287A4E4E0CCA21D0069C1C] [2023-11-03T17_10_13.3433782-07_00]]/Steam/coplay_76561199204857772.vdf. Skipping...

Even tough it is extracting passes, cvv and links, but it's not parsing it correctly, i guess it's Rebelion stl. Any suggestions ?

**Comment by milxss** [comment]
Hi, the parser is skipping the files you shared from the log because they are not text files.

**Comment by myusernameis69** [comment]
Indeed, stupid me haha :D when i'll have some time, i'll make it read non text files as well, different encodings.

**Comment by milxss** [comment]
> Indeed, stupid me haha :D when i'll have some time, i'll make it read non text files as well, different encodings. 

That's not stupid at all, thank you for leaving a comment, by the way. I appreciate that. I would be curious to see your implementation :) unfortunately me too, I lack time for this mini-project. There are lots of things to add here and improvements to make.
